DATA:
  train_name: pascal
  test_name: default
  train_split: 0
  test_split: default
  train_list: lists/pascal/train.txt
  data_root: ../dataset/VOCdevkit/VOC2012
  val_list: lists/pascal/val.txt
  num_classes_tr: 16  # Counting background for training
  num_classes_val: 5
  use_split_coco: False
  workers: 2
  image_size: 473
  padding_label: 255
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  scale_min: 0.5
  scale_max: 2.0
  rot_min: -10
  rot_max: 10
  augmentations: ['hor_flip', 'vert_flip', 'resize']

TRAIN:
  ckpt_path: checkpoints/
  batch_size: 12
  epochs: 100
  log_freq : 50
  save_models: True
  lr: 0.0025
  cls_lr: 0.1
  scale_lr: 2.0
  mixup: False
  lr_stepsize: 30
  momentum: 0.9
  gamma: 0.1
  nesterov: True
  weight_decay: 0.0001
  main_optim: SGD
  scheduler: cosine
  milestones: [40, 70]

MODEL:
  arch: resnet
  pretrained: True  # Means the backbone has been pre-trained
  bins: [1, 2, 3, 6]
  dropout: 0.1
  m_scale: False
  layers: 50
  bottleneck_dim: 512

EVALUATION:
  episodic_val: False
  shot: 1
  random_shot: False
  norm_feat: True
  batch_size_val: 200
  manual_seed: 2021
  ckpt_used: best
  test_num: 1000
  FB_param_noise: 0
  smoothing: True
  n_runs: 2
  save_oracle: False

CLASSIFIER:
  dist: dot
  cls_type: ooo
  adapt_iter: 200


EXPERIMENT:
  exp_name: pretrain_dot_val